version: '3.8'

services:
  app:
    build: .
    ports:
      - "80"
    volumes:
      - coti-uploads:/var/www/html/assets/images/profile
    links:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      DB_HOST: db
      DB_USER: coti_admin
      DB_PASS: 13117531
      DB_NAME: coti_db
      SERVICE_PASSWORD_MYSQL: 13117531
      MYSQL_DATABASE: coti_db
      MYSQL_ROOT_PASSWORD: 13117531
    ports:
      - "3306:3306"
    volumes:
      - coti-db-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  coti-db-data:
  coti-uploads:
