version: '3.8'

services:
  app:
    build: .
    ports:
      - "80"
    volumes:
      - ./src:/var/www/html
      - coti-uploads:/var/www/html/assets/images/profile
    links:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: coti_db
      MYSQL_ROOT_PASSWORD: 13117531
    ports:
      - "3306:3306"
    volumes:
      - coti-db-data:/var/lib/mysql

volumes:
  coti-db-data:
  coti-uploads:
